# Generated by Django 6.0.6 on 2026-06-19 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Unidade')),
                ('sigla', models.CharField(max_length=20, unique=True, verbose_name='Sigla')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Responsável pelo Envio')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail de Contato')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDescarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('toner', 'Toner'), ('unidade_imagem', 'Unidade de Imagem'), ('cartucho', 'Cartucho'), ('periferico', 'Periférico de Informática (Mouse, Teclado, etc.)'), ('armazenamento', 'Unidade de Armazenamento (HD, SSD)'), ('pilha', 'Pilha'), ('bateria_nobreak', 'Bateria de Nobreak'), ('lampada', 'Lâmpada')], max_length=30, verbose_name='Categoria do Material')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo / Descrição do Material')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Envio'), ('recebido', 'Recebido na Triagem'), ('descartado', 'Descartado Corretamente')], default='pendente', max_length=20, verbose_name='Status do Descarte')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.unidade', verbose_name='Unidade de Origem')),
            ],
        ),
    ]
