# Generated by Django 6.0.6 on 2026-06-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdescarte',
            name='unidade',
            field=models.CharField(max_length=100, verbose_name='Unidade da UFPA / Setor'),
        ),
        migrations.DeleteModel(
            name='Unidade',
        ),
    ]
