# Generated by Django 5.2.18 on 2026-10-07 17:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_alter_materialdescarte_unidade_delete_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProcessado',
            fields=[
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro processado',
                'verbose_name_plural': 'Registros processados',
            },
        ),
    ]
