# Generated by Django 5.2.18 on 2026-10-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_registroprocessado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdescarte',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
